### ISSUE TITLE
Allow providing custom project npm/yarn settings

### ISSUE THREAD

**Issue by maybeec** [devonfw/devon-ide#112]
NPM and Yarn settings are provided by local .npmrc config file.
We should be able to have such a configuration for an IDE by default enable a project to adapt the configuration to enter custom npm repositories for example. Here an example which environment variable to set for a custom configuration file:

NPM_CONFIG_USERCONFIG=%CD%/%CONF_PATH%/ide-settings-npm-yarn/.npmrc

**Comment by hohwille** [comment]
Thanks for this feedback and input.
If I got you right the project may put this into their `$DEVON_IDE_HOME/conf` folder. I would rather put `.npmrc` directly there ommiting this strange `ide-settings-npm-yarn` subfolder (or is there any rationale for that?).

What will happen if that .npmrc file does not exist or is empty?
If that is tolerated, I would suggest to always export this environment variable `NPM_CONFIG_USERCONFIG` via `devon.properties` as `${DEVON_IDE_HOME}/conf/.npmrc` and we are done. We could like we do with maven introduce a template that projects can define in their `settings` git repo.

**Comment by maybeec** [comment]
The reason for the ide-settings-npm-yarn folder was the idea to sharing the config (maybe even more in future) by git.
You could also follow the more easier approach you posted, but this would remove the ability to share the config by git.
In general, I am using the same mechanism for sharing settings for all available settings and wanted to implement an update script in future, which does a pull on all these respositories automatically. Therefore, I was using a common mechanism like git to have a common way of sharing all different settings.

**Comment by hohwille** [comment]
Okay. The idea with devon-ide is that the settings come from a git repo and can therefore be shared. However, the user should also have its freedom to tweak and customize configs rather than being dictated too much from what comes from the git repo. Therefore we put templates in the settings git and use them to initialize the ide by copying the templates to the users `conf` folder.
We already do the same for the `settings.xml` from maven. So is your suggestion to have a sub-folder like `.m2` for maven also for npm and yarn settings inside `conf`?
I would like to use something more natural then. So if the variable is named `NPM_CONFIG_USERCONFIG` why should we just name the folder `conf/npm` or `conf/.npm`? The name `ide-settings-npm-yarn` seems a bit artificial and over-engineered to me.

**Comment by hohwille** [comment]
What would be the content of such `.npmrc` file?
Can you give us some examples how a template may look like?

**Comment by maybeec** [comment]
Private registry information for example : https://stackoverflow.com/questions/49404870/how-to-set-auth-for-a-scoped-registry-in-npmrc

**Comment by maybeec** [comment]
Totally fine to rename it.

**Comment by hohwille** [comment]
Hope the solution suites your needs.
Closing this issue after PR #130 has been merged.

**Comment by markusschuh** [comment]
The NPM_CONFIG_USERCONFIG in devon.properties does not yet point to the path, where the default template file is installed:

${DEVON_IDE_HOME}\npm\.npmrc  vs. 
${DEVON_IDE_HOME}\conf\npm\.npmrc

I should probably open a pull request for this,  but for such one-line-changes the effort seems still a bit high to me.

**Comment by hohwille** [comment]
> I should probably open a pull request for this, but for such one-line-changes the effort seems still a bit high to me.

There are almost none:
* got to the file on github in web-browser.
* click on "pencil" icon.
* edit file content in browser and fix the bug
* click create feature branch
* click new pull request
* done.

**Comment by hohwille** [comment]
Seems as @markusschuh is talking about this:
https://github.com/devonfw/devon-ide/blob/1bfa19732af7f435c7945eee2178d915422ddbac/scripts/src/main/resources/scripts/devon.properties#L15

should indeed be `conf` instead of `npm`. Thanks for notifying this bug 👍 
Will fix it asap.

**Comment by hohwille** [comment]
Fixed with PR #184.
