### ISSUE TITLE
SoapUI is causing entire eclipse to freeze on rightclick on project

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon-ide#120]
Due to some strange dead-lock situation with `com.eviware.x.impl.swt.support.AwtEnvironment` (from SoapUI) a I right click on projects  causes my entire eclipse to freeze and stall making it useless.

**Comment by hohwille** [comment]
As I have finally enough with things like this, I have to agree to what Malte was already saying and proposing:
We should only install a minimum and stable set of required plugins for eclipse by default. Users/projects can install whatever they want but nobody should get a wirde plugin that renders his eclipse useless. Lets get rid of SoapUI, SonarLine, STS, Lombok, etc.

**Comment by hohwille** [comment]
I just checked and these plugins are no more installed by default already.
https://github.com/devonfw/devon-ide/blob/master/scripts/src/main/resources/scripts/command/eclipse#L57
So the current list is:
* startexplorer
* regexutil
* templatevariables
* spotbugs
* checkstyle
* cobigen
* terminal

(while cobigen and tm-terminal are not yet working)
Should we also omit any of these?
* templatevariables
* spotbugs
* checkstyle

**Comment by maybeec** [comment]
for me sonar and checkstyle is critical as well as QuickSearch.

**Comment by hohwille** [comment]
We have tons of issues with SonarLine. It is fine if projects configure this plugin in their project settings via git but IMHO this should not come by default. We can change our mind once it has reached better quality (does not slow down the entire IDE like hell and does not break IDE either).

For checkstyle I will leave it in. It does not hurt and is stable for years.

QuickSearch is not included by default but we can try to do so.

**Comment by hohwille** [comment]
The actual issue was to exclude SoapUI which is already done. As we also do not need more exclusions, I will close this. Feel free to create PR adding QuickSearch by default.
