### ISSUE TITLE
The per default generated workspaces/readme.txt need some updates

### ISSUE THREAD

**Issue by markusschuh** [devonfw/devon-ide#123]
Category: Bug

Severity: Low

Expected behaviour: The content of readme.txt should be consistent with the current status of devon-ide 

Actual/current behaviour: There are some references to outdated parts. (e.g. variables.bat )

**Comment by markusschuh** [comment]
Some quick'n a bit dirty review of the original text:

Inside this directory you create your workspaces. Typically one for each branch. There is always one MAIN_BRANCH such as head, master, or trunk. You can add any new workspace by creating another folder here. 
Change to any of those workspace and call "devon eclipse ws-update" to initialise/update it. Call "devon eclipse create-script" to create an eclipse-<workspace> start script in devon top directory.
You can checkout the according branch to that workspace folder and import the projects into the corresponding eclipse instance. The workspace name is also visible in the title-bar of Eclipse so you get orientation when you have multiple instances of eclipse running simultaneously.

**Comment by hohwille** [comment]
Done.
https://github.com/devonfw/devon-ide/blob/master/scripts/src/main/resources/workspaces/readme.txt
