### ISSUE TITLE
Extend IDE commandlets to update all workspaces

### ISSUE THREAD

**Issue by ediekman** [devonfw/devon-ide#135]
Category: Enhancement

Currently you have to execute commands like create ´ws-up[date]´, ´create-script´ for each workspace by switching in the according folder. In future it should be possible to use an additional parameter (e.g. -all) to execute these commandlets for all workspaces of eclipse.

**Comment by hohwille** [comment]
If that is implemented, it would make sense, to do this not only for `eclipse` but for all IDE commandlets (also `intellij` and `vscode`).

**Comment by hohwille** [comment]
According to GNU conventions option should be `-a` or `--all`.

**Comment by hohwille** [comment]
Done with PR #164
