### ISSUE TITLE
Document target for 'devon' command

### ISSUE THREAD

**Issue by nricheton** [devonfw/devon-ide#173]
Category: Enhancement
Severity: Medium
Description of issue / expected enhacement /Comments : 

Documentation should explain the plan for devon-ide/devon command in comparaison of devonfw/devon command.   (ie. replace it)

Currently devon-ide/devon doesn't support the same instruction set than devonfw/devon. 

This is really confusing for new users. 

Nicolas

**Comment by hohwille** [comment]
IMHO you are talking about devcon with the "old command" that may have had an alias "devon".
We descided for a clean redesign with devon-ide. I had a yammer posting and was asking the entire communtiy for feedback about the new CLI. I presented this in the DA Meeting, etc.

To be straight forward my personal statement is that I will reject this issue. This feedback is just too late and sometimes we have to get over some changes. We had much more confusion and hussle when going from OASP to devonfw. It is all forgotten and history now.
If you disagree provide a PR or find someone to do so. IMHO the new CLI is better and more intuitive. There is even already a large new userbase with devon-ide that would be even more confused if we now change the CLI.

Feel free to have a differrent opinion and start a further discussion to convince me or others of your proposal.

**Comment by hohwille** [comment]
Sorry, I was to fast in closing issues. I now got what you actually want:
You are proposing to update some documentation to explain this better.
Can you be more concrete about this?
Can you link which place in the documentation you are thinking of?
Are you proposing some documentation as a table with
old-command vs. new-command?

**Comment by markusschuh** [comment]
I fully agree with Nicolas. For some tasks it is not yet clear to me, how I need to do them with help of devon-ide. I assume a full table "old vs. new" were too much work, but at the least for the most used commands such a migration-helper should exist.

I have tried to identify, what commands the old devonfw 2.4.x has supported - this list may be some starting point for such a table.

devcon workspace  create
devcon project    create
devcon project    build
devcon project    run
devcon devon4j    create
devcon devon4j    build
devcon devon4j    run
devcon devon4j    deploy
devcon devon4j    migrate
devcon devon4ng   create
devcon devon4ng   build
devcon devon4ng   run

devcon system     configureEnvironment
devcon system     installDevcon
devcon dist       info
devcon dist       init
devcon dist       install
devcon dist       s2

devcon doc        devon
devcon doc        devon4jguide
devcon doc        devonguide
devcon doc        getstarted
devcon doc        links
devcon doc        userguide
devcon github     devon4j
devcon github     devoncode
devcon help       command
devcon help       module
devcon help       overview
devcon help       userguide

console
ps-console.bat
variables
eclipse-examples
eclipse-main
vscode-workspaces_vs

update-all-workspaces
create-or-update-workspace
create-or-update-workspace-vs

s2-init
s2-create

**Comment by hohwille** [comment]
FYI: I asked the spanish guys several times already what `s2-*` is good for and never got an answer. So do not expect me to document this. I am unable to.

For the rest I will try to give a first shot.

**Comment by hohwille** [comment]
So here is my proposal:
https://github.com/devonfw/devon-ide/blob/master/documentation/migration-from-devonfw-3.0.0-or-lower.asciidoc

Contributions and improvements are most welcome.
As stated in the TODO it would be a cool enhancement if we could support the upgrade from the old IDE to the new one by just extracting the new devon-ide on top of the old one and run the `setup` script. I will file a separate issue for this.

**Comment by hohwille** [comment]
I will now close this issue as the actual feature request has been addressed.
If you still miss something provide a PR to improve the documentation (you can edit online in the browser with "pencil" icon and provide a PR with just a few clicks) or file a new issue.
