### ISSUE TITLE
duplicate warnings on initial setup

### ISSUE THREAD

**Issue by maybeec** [devonfw/devon-ide#177]
Category: Bug or enhancement
Bug

Severity: Low , Medium, High, Critical
Medium

Expected behaviour (In case of bug)
If there is no settings path and no software package available, I will be asked after another to serve the download paths or simply continue to take some default from the internet.

Actual/current behaviour (In case of bug)
Currently I have multiple `*** ATTENTION ***` warnings continuing progressing something, that i think I made something wrog. Finally, the settings URL is asked by the system. Why is there so much attention needed if it is the default behavior. It seems like warnings.

In general from a user perspective, it is quite hard to differentiate the log from the system and the actual text necessary to be read by the user as of a question to be answered. It would be nice if logs could be somehow differentiated for example by a leading > or anything like this. 

Steps to reproduce (In case of bug)
Download beta.11 and run the setup

Description of issue / expected enhacement /Comments

Your environment - windows/Linux, Devonfw version , component
windows7

**Comment by maybeec** [comment]
Just as another example, there comes a text `To be fully functional please rerun 'devon' command to update your PATH properly.` i the middle of the dowloading and setting up mvn. I would bet, that nobody is reading it as there is so much text.

couldn't it be even more sutable to make 90% of the logs just visible on a --verbose flag? I am just interested in the progress and on the step being progressed at the moment. Nothing more ;)

**Comment by hohwille** [comment]
Use `-q` option for quiet output.
Everything else you are complaining here is prio minus infinity for me at the moment.
I also disagree that a an extra error log output is a bug. A bug means that something is not working.
Thanks for the feedback. I am just frank with my straight answer to clarify the expectation how fast these issues will be fixed. This project has already eaten tripple of my resources planned for it and so far I still have no other developers working on this.
Feel free to provide pull requests.

**Comment by maybeec** [comment]
Ok, totally agree about the priority of this.
Anyhow, for the one who is implementing this later. It would be better to always put less into the log. Just what is necessary to be read by the user by default. If he wants to get more, you can simply provide a --debug or --verbose flag. The other way around with the quite flag does not make sense to me and would disturb 90% of the users.

**Comment by hohwille** [comment]
I think there is still a trade-off to make.
Users will like the status output from `curl` when downloading tools as otherways they might think the installer crashed or hangs. However, already such output is already quite verbose.
Further bash is often creating very poor error messages with limited contect info.
You also need to be aware that I have to be able to give support for users running into issues.
If I only get `mvn: command not found` or `ln: failed` I will be puzzled but unable to assist.
That is why I created this `doRunCommand` stuff that first prints out the command that is going to be executed with all args and then reports exit codes, etc.
Please be aware there is nothing such as a Java Exception in bash...

**Comment by hohwille** [comment]
What we could do is actually write a real logfile and put the major details there and have only minimal output on stdout. But sill I would suggest to output download progress to end-users.

**Comment by maybeec** [comment]
Yes totally agree to your last statement. This should be the best of both worlds.
Interestingly, during a usability study of the cobigen cli ohne of the most often mentioned requirement was 'it should be colorful and Easy to read' ;)

**Comment by hohwille** [comment]
Was autoclosed by github from commit comment.
However, actual issue is indeed fixed. File new issue to request advanced logging features.
