### ISSUE TITLE
cmd windows not closing on eclipse startup

### ISSUE THREAD

**Issue by maybeec** [devonfw/devon-ide#180]
Category: Bug or enhancement
Bug

Severity: Low , Medium, High, Critical
High

Expected behaviour (In case of bug)
The initiating cmd window as well as the command window of eclipse.exe should vanish if eclipse is launched.

Actual/current behaviour (In case of bug)
executing eclipse-main.exe results in the two windows keep open until you close eclipse again. This is messing up the windows on each machine.

![grafik](https://user-images.githubusercontent.com/1427255/63023445-6f6ff400-bea5-11e9-8c85-83f7ce67b1df.png)

Steps to reproduce (In case of bug)
run eclipse-main.exe, two windows are opened and eclipse.

Description of issue / expected enhacement /Comments

Your environment - windows/Linux, Devonfw version , component
win7

**Comment by hohwille** [comment]
I assume it is the `call` command:
https://github.com/devonfw/devon-ide/blob/ed65ea578340107b1a6ae53192bd40bb9c26c4d7/scripts/src/main/resources/scripts/functions#L854

Can some windows guy play around with the eclipse-*.bat script and let me know it it works if we just remove the "call" in front of the devon command?

**Comment by hohwille** [comment]
Was autoclosed by github due commit comment.
Manual retest with beta14 on windows confirmed it is working for
* windows CMD
* git-bash (MINGW)

However it fails on cygwin:
```
$ devon eclipse
ERROR: DEVON_IDE_HOME does not exist!
/cygdrive/c/projects/beta5
It seems as if you original installation has been moved.
Unknown command eclipse
```

And trying to test it in powershell reveals that with new windows 10 also PowerShell integration is broken. I get a popup:
```
This file does not have a program associated with it for performing this action. Please install a program or, if already installed, create an association in the Default Programs control panel.
```

Both latter bugs have nothing to do with this fix. I will file new separate issues for that.
