### ISSUE TITLE
issue with devon-ide installation on Ubuntu

### ISSUE THREAD

**Issue by Rohit90700** [devonfw/devon-ide#196]
Category: Bug or enhancement

Severity: Low , Medium, High, Critical

Expected behaviour (In case of bug)

Actual/current behaviour (In case of bug)

Steps to reproduce (In case of bug)

Description of issue / expected enhacement /Comments

Your environment - windows/Linux, Devonfw version , component

**Comment by Rohit90700** [comment]
Hi @hohwille ,
During the testing of devon-ide-scripts-3.0.0-beta12.tar.gz  found some issues when executing setup on terminal -
1) .git command is not found
2)  cURL command not found 

Both of them need to install manually. one more issue i found in beta11 related to the .xz extension which is resolved in beta12.

**Comment by hohwille** [comment]
@Rohit90700 thanks for the feedback.
As you can read here:
https://github.com/devonfw/devon-ide/blob/master/documentation/setup.asciidoc#prerequisites

> This also ships with bash and curl on Windows what also is required and should be present on all other platforms.

So it is not really a bug but however a wrong assumtion. I was not aware that Ubunutu is so crappy. At least curl is supposed to be present on all modern unix platforms.
So could you install these two tools and note down the command(s) to do so (e.g. `sudo apt-get install git curl`). Then it would be awesome if you could update the above prerequisites so it fits for linux (esp. ubuntu) as well (so saying that you need `git` and `curl` as a prerequisite and then having a bullet or sub-section per platform telling what is needed to assure this)?

You can do the changes online in the browser by clicking on the `pencil` icon on the asciidoc file, edit your changes, submit as branch and then click create pull-request. That would be awesome.

**Comment by hohwille** [comment]
Documentation updated with PR #205
