### ISSUE TITLE
assembly descriptor contains unix specific root-relative-reference

### ISSUE THREAD

**Issue by markusschuh** [devonfw/devon-ide#2]
Category: Bug

Severity: Low

Expected behaviour: No *ERROR* level logs during `mvn install`

Actual/current behaviour: Several messages like
> [ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference (starting with slash) /

Steps to reproduce:  Run `mvn install` in fresh cloned `devon-ide`

Description of issue / expected enhacement /Comments:
see https://stackoverflow.com/questions/32604733/error-os-windows-and-the-assembly-descriptor-contains-a-nix-specific-root-relat

Your environment - windows/Linux, Devonfw version , component:
devon-3.0.0-SNAPSHOT
Windows, Apache Maven 3.5.4, Java version: 1.8.0_181, vendor: Oracle Corporation

**Comment by hohwille** [comment]
Fixed with PR #4 that has been merged. Hence done.
