### ISSUE TITLE
issues in /documentation/usage.asciidoc

### ISSUE THREAD

**Issue by phschimm** [devonfw/devon-ide#214]
issues:

* following the instructions in [step 3](https://github.com/devonfw/devon-ide/blob/master/documentation/usage.asciidoc#working-with-multiple-workspaces) results in launch-scripts with the **name** of the new workspace, however these scripts open an Eclipse/VSCode instance pointing to the "main" workspace

broken/wrong links:

* "We assume you have successfully installed it first."
  * [installed](https://github.com/devonfw/devon-ide/blob/master/documentation/install.asciidoc) link leads to a non-existing file
* "Go to the workspaces folder in your ${DEVON_IDE_HOME} [...]"
  * [${DEVON_IDE_HOME}](https://github.com/devonfw/devon-ide/blob/master/documentation/variables) link should refer to [variables.asciidoc](https://github.com/devonfw/devon-ide/blob/master/documentation/variables.asciidoc)
* "You can also add the parameter create-script to the IDE commandlet [...]"
  * [commandlet](https://github.com/devonfw/devon-ide/blob/master/documentation/cli.asciidoc#commandlets) link should lead to [cli.asciidoc#commandlets](https://github.com/devonfw/devon-ide/blob/master/documentation/cli.asciidoc#commandlets)

realted notes:

* new users might be confused about what to do in [step 2](https://github.com/devonfw/devon-ide/blob/master/documentation/usage.asciidoc#working-with-multiple-workspaces), since `checkout` in most other VCS' is synonimous with `git clone` (which they are instructed to install), Git however also offers the command `git checkout` ...

**Comment by hohwille** [comment]
@phschimm thanks for your constructive feedback. 👍 

FYI: You could be even more supportive if you directly fix the documentation online:
0. ensure you have a github user and are logged in
1. go the the documentation with your browser. E.g. https://github.com/devonfw/devon-ide/blob/master/documentation/usage.asciidoc
2. click the pencil icon
3. do the changes/fixes
4. if you want click on the preview tab to check that all looks correct now
5. go to the bottom of the page and create a new branch with your change
6. click on create pull request
7. submit the pull request

Please try it next time. It is super easy. Then I can see the diff of your changes and if all suites fine, I can just click merge and we are done. Explaining in detail which link is broken and should be changed how is IMHO more work that immediately fixing it (for you and me).

**Comment by hohwille** [comment]
The fist aspect of this issue is not related to the documentation.
However, I retestet this and cannot confirm your bug report in this regard.
Which version of `devon-ide` where you using?
Can you retest and file a new individual issue only for that problem in case you can still reproduce this error (even with the latest beta version)?

**Comment by phschimm** [comment]
I agree, I'll follow these steps next time (still learning Git/GitHub).
I was using beta17, but I'll retest it again and open another issue if the problem persists for me.

**Comment by hohwille** [comment]
Fixed with PR #221
