### ISSUE TITLE
maven archetype-catalog.xml buggy

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon-ide#240]
Maven has a catalog for archetypes e.g. to detect the latest version or for GUIs to create search and auto-completion/content-assist for archetype selection:
https://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype-catalog.html

There is a central catalog maintained in maven central repo:
http://repo.maven.apache.org/maven2/archetype-catalog.xml

However, the process of staging releases to maven central and updating the archetype catalog seems buggy or broken. Therefore we deploy releases to maven central but the archetype catalog then does not get updated accordingly.
Currently we have released `devon4j` in version `3.1.1` providing this archetype:
http://repo.maven.apache.org/maven2/com/devonfw/java/templates/devon4j-template-server/3.1.1/

However the central archetype catalog only contains versions of that archetype until version `3.1.0`:
http://repo.maven.apache.org/maven2/archetype-catalog.xml

See also:
https://maven.apache.org/archetype/maven-archetype-plugin/specification/update-catalog.html

**Comment by hohwille** [comment]
Please note that this is a bug in the maven ecosystem and not of `devon-ide`. It has already been reported but gets ignored:
https://issues.apache.org/jira/browse/ARCHETYPE-312

Getting such external bugs fixed can take ages - see e.g.:
* https://issues.apache.org/jira/browse/MRESOLVER-90
* https://issues.apache.org/jira/browse/MNG-4161
* https://issues.apache.org/jira/browse/MNG-6656

So as I am tired of this, I will create a simple workaround:
* when the archetype gets created in `devon-ide` and no `archetypeVersion` property is provided, I will download the `maven-metadata.xml` of the exact GA coordinates of the archetype to be installed and then grep the latest version from there. I will simply add that version as `-DarchetypeVersion=${archetypeLatestVersion}` and can close this issue.

**Comment by vapadwal** [comment]
We have created the issue in maven central for the same
https://issues.sonatype.org/browse/MVNCENTRAL-5148
