### ISSUE TITLE
reduce exposing of devon-ide scripts' variables to environment

### ISSUE THREAD

**Issue by markusschuh** [devonfw/devon-ide#5]
Category: Enhancement

Severity: Low 

Description of expected enhancement: The current refactoring is a good opportunity to reduce the a bit too generous use of external environment variables by the IDE scripts a bit. Even when those variables are only defined within the workspace consoles - and everything what is started from there - there is a small risk of unnecessary side effects, when variables of local scope like "MODE" are exposed to outside.

**Comment by hohwille** [comment]
done.
Documentation can be found here:
https://github.com/devonfw/devon-ide/wiki/varibales
