### ISSUE TITLE
set of DEVON_IDE_HOME needs some path canonisation

### ISSUE THREAD

**Issue by markusschuh** [devonfw/devon-ide#68]
Category: Bug

Severity: Low

Expected behaviour: Calling "devon help java" should output only one line for value of DEVON_IDE_HOME.

Actual/current behaviour:
Currently I get:
> DEVON_IDE_HOME variable set to /sw/devon-ide-scripts-3.0.0-beta2devcon/scripts/command/../..
...
> DEVON_IDE_HOME variable set to /sw/devon-ide-ide-scripts-3.0.0-beta2/scripts/command/../../scripts/command/../..

Steps to reproduce: 
run "devon help java"

Comments:
The two output variable values result in the same path - so this isn't a functional issue - but it would be easier to read, if the relative parts of the path would be resolved, e.g with help of 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 
as described on 
https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself

The output of the variable is generated at the end of "functions", which is called twice (from commands/help and commands/java). 

environment - macOS, devon-ide-scripts-3.0.0-beta2

**Comment by hohwille** [comment]
Strange bug. However, I assume that this is already fixed some days ago and I just need to push out a new release (3.0.0-beta3). On my MacOS machine I can not reproduce this problem.

**Comment by hohwille** [comment]
Fixed.
