### ISSUE TITLE
devon.bat fails to find reg in PATH

### ISSUE THREAD

**Issue by markschuh** [devonfw/devon-ide#77]
Category: Bug
Severity: High

Expected behavior: 
initial 'setup' execution should add 'devon.bat' to (default) PATH

Actual/current behavior: 
output of setup.bat contains:
```
...
Der Befehl "reg" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Der Befehl "setx" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
The devon CLI script has been installed to your windows system.
...
```
Steps to reproduce: 
I have built my own devon-ide-scripts-3.0.0-beta3-SNAPSHOT.tar.gz with mvn from commit a4d8c37dd391121d07e8620f52308169a80ebf1d and extracted it. Finally run 'setup' from within the extracted directory

Description of issue:
Three lines before the CMD tries to use 'reg' - and a bit later 'setx' - there is the command:

    for %%f in (devon.bat) do set "path=%%~$PATH:f""

This either sets "path" var to the single directory in PATH, where a devon.bat already exists - or an empty value. Both results will be handled correctly within the following if condition - but even when CMD keeps the case of variables on set: path overwrites PATH (and vice versa). With "PATH=" the batch can not find the external tools. 
Solution: use devon_bat_path instead of path
And it is also a good practice within scripts to call executable from windows systemroot with explicit path in such scripts. Or otherwise ensure, that "%SystemRoot%\system32 is first in PATH inside script,

My environment: 
Windows 10 Pro (German) devon-ide-scripts-3.0.0-beta3-SNAPSHOT

**Comment by hohwille** [comment]
Thanks for the feedback. Intereseting that I can not reproduce this bug, as I also use Win10 Pro (English) inside VMWare fusion on MacOS.
However, you are fully correct:
https://github.com/devonfw/devon-ide/blob/5079872a21b584a6afd7caac0fd3d2c9557e1caa/scripts/src/main/resources/scripts/devon.bat#L16

**Comment by hohwille** [comment]
I am not an expert in windows CMD hacking and have to admit that I rather hate it as it is ugly and error-prone. That is also why I designed the new devon-ide such that only a minimum of the functionallity is done with windows CMD and everything else is done in BASH in a cross-plattform way.

**Comment by hohwille** [comment]
Fixed.
