### ISSUE TITLE
Install devonfw extension pack to vscode automatically

### ISSUE THREAD

**Issue by hohwille** [devonfw/devon-ide#99]
Like with Eclipse we should support to automically install plugins for VS Code. The default should be our extension pack:
https://github.com/devonfw/devonfw-extension-pack-vscode

The scripting of the installation is simple:
```
code --install-extension «extension-ID»
```

**Comment by hohwille** [comment]
Already figured it out from here:
https://marketplace.visualstudio.com/itemdetails?itemName=devonfw.devonfw-extension-pack
We need to call this command:
```
code --install-extension devonfw.devonfw-extension-pack
```

**Comment by hohwille** [comment]
If have implemented this as planned and also fixed the VS Code for MacOS (as always MacOS is lacking compatiblity with other plattforms as Apps are handled totally different there, so we manually create a `code` launch script in `bin` folder to make it compatible with windows and linux).
The issue I am still facing is that (unlike with eclipse) the `--install-extension` feature is working in the foreground. Hence VS code app is started and does not even end automatically after installation. Currently the user has to shutdown the VS Code IDE to make the script continue.
We could either run the installation as a background process and consider this as a feature (`devon setup` will then automatically launch VS Code) or we need to try to find a way link with eclipse to tell VS Code to shut down automatically after installation and if possible even run headless.

**Comment by hohwille** [comment]
IMHO running in background is a simple solution (KISS).
However, now I am seeing this error:
```
[main 2019-05-07T10:08:37.161Z] Error: listen EEXIST /Users/hohwille/Library/Application Support/Code/1.31.1-main.sock
    at Server.setupListenHandle [as _listen2] (net.js:1313:19)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1477:5)
    at /projects/devon/software/vscode/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:186:590
    at new Promise (<anonymous>)
    at Object.t.serve (/projects/devon/software/vscode/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:186:523)
    at r (/projects/devon/software/vscode/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:531:869)
    at F (/projects/devon/software/vscode/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:534:386)
    at t.e.invokeFunction (/projects/devon/software/vscode/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:222:588)
    at /projects/devon/software/vscode/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:536:234
```
It would be lovely if users of the JS ecosystem could also test and contriubte to devon-ide.

**Comment by hohwille** [comment]
Does the error mean that the extension-pack is already installed?
I just deleted the `software/vscode` folder and run `devon vscode setup` again.
Where does VS Code install its extensions?
Any help? Somebody? I am not a real user of VS Code...

**Comment by sjimenez77** [comment]
Hi @hohwille,

The error says that the `1.31.1-main.sock` file already exists. AFAIK this file is the socket stream file that VS Code uses to update itself. Maybe it is not removed properly or a previous update process got stuck.

In order to know where the extensions are downloaded and installed you can check this link https://vscode-docs.readthedocs.io/en/stable/extensions/install-extension/ 

Best regards,
Santos

**Comment by hohwille** [comment]
@sjimenez77 thanks for your feedback. Valuable input that is very much apreciated!
So indeed my installation process got stuck and it seems the socket file was not cleaned. I will do some more testing and see if I can improve the behaviour to avoid others running into this error.
Otherwise I am done with this issue and will close as soon as PR is merged.

**Comment by hohwille** [comment]
Done with PR #105 now
